### ISSUE TITLE
Upgrading to react-hot-loader@4.2.0 breaks the app

### ISSUE THREAD

**Issue by joacim-boive** [supnate/rekit#130]
I think it's a react-hot-loader issue, but it can be good to know about in the project since it took some time to find out.

Read more about it here: https://github.com/gaearon/react-hot-loader/issues/986

**Comment by supnate** [comment]
Thanks @joacim-boive for reporting this. But the error seems caused by DLL bundle not loaded. Can you check if the global variable `devVendors_xxxx` exists? The variable should not be related with RHL since it's loaded in a separate `<script>` tag. And could you please check `<prj-root>/.tmp/dev-vendors.js` if the variable is the same as which in error message? If not, remove `.tmp` folder and restart dev server.
