### ISSUE TITLE
Using dotenv files in the browser

### ISSUE THREAD

**Issue by Remimstr** [supnate/rekit#145]
Sup supnate!

Thank you for this awesome tool. I've been using it at work for the last month or so and I think it's really great! Usually I can resolve any sort of config issue but one thing I struggled with today was getting environment variables working in the browser.

I noticed that you use the package "dotenv" so I figured adding a new variable should be as easy as creating a .env file and adding the variables I want. Unfortunately I can't see the variables I want on process.env

Do you have any recommendations for how I should get this working? Thank you!

**Comment by supnate** [comment]
Hi @Remimstr , glad to know you're using Rekit at work, any feedback is welcome.
Rekit supports dotenv just like how create-react-app supports it: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables
You need to prefix your env variable with "REACT_APP_" so that they will be accessed in browser, like:
```
REACT_APP_DB_HOST=localhost
REACT_APP_DB_USER=root
REACT_APP_DB_PASS=s1mpl3
```

**Comment by Remimstr** [comment]
That was exactly what I needed, thank you so much for your help & for giving me such a quick response!
