### ISSUE TITLE
Stateless Functional Components

### ISSUE THREAD

**Issue by Remimstr** [supnate/rekit#146]
Hi Supnate!

As you know, I've been using Rekit at work (I love it!) and I've been thinking about ways to improve it further. One thing I'd love to see it support is [Stateless Functional Components](https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc) because while I've been using these in my codebase, Rekit doesn't identify them as components and instead lumps them into the "misc" folder, which seriously hurts the flow of creating, styling, and testing such components.

I would be interested in discussing a possible implementation for this feature and trying to implement it myself. If all goes well, I would consider contributing more to this project because I think it really is that cool! Let me know what you think.

**Comment by supnate** [comment]
Thanks @Remimstr ,

Currently Rekit detects a component when it imports 'react', and exports a class with render method. You can see the code at: https://github.com/supnate/rekit/blob/master/packages/rekit-core/core/app.js
```javascript
const props = {
    component: ff.importReact &&
      ff.hasClassAndRenderMethod && {
        connectToStore: ff.connectCall,
      },
    action: ff.exportReducer &&
      ff.importConstant && {
        isAsync: ff.importMultipleConstants,
      },
  };
```

Yes, it's too limited. I agree we need to improve it. One quick idea in my mind is it imports 'react' and has a style file 'Component.less'. If you would like to try it, a PR is welcome:-)

BTW, Rekit is under heavy refactoring so that it will support a complete plugin system. At that time the current CRA based project boilerplate will be a plugin of Rekit. It will still compatible with the existing Rekit projects.

**Comment by Remimstr** [comment]
Ok that sounds good! I've gotten pretty busy at work so I may not get around to working on this for a couple of weeks. I'll keep it in mind though :)

**Comment by supnate** [comment]
Sure, no problem, take your time:)

**Comment by Remimstr** [comment]
Hi supnate, I was just about to start looking into this (work has finally slowed down a bit) but it looks like you're in the middle of a pretty big refactor. I just wanted to let you know I'm still thinking about this project and I'm excited for your 3.0 release!

**Comment by zedtux** [comment]
Hey guys, I'm looking for exactly this thing. Any news here?

**Comment by Remimstr** [comment]
To be honest, I don't think I'll ever do this. I've moved our project at work away from rekit as the limitations of the tool began to conflict with my architectural decisions. And unfortunately I simply don't have the time or understanding to update/extend rekit quickly enough for my use cases.

**Comment by barrygilbert** [comment]
I found I needed this exact thing while refactoring a project yesterday, so here is the PR for it. Pretty small update and appears to work consistently running on Ubuntu.

**Comment by zedtux** [comment]
Awesome ! Thank you @barrygilbert !
