### ISSUE TITLE
Re-add webpack dashboard

### ISSUE THREAD

**Issue by rjharmon** [supnate/rekit#18]
Readme refers to webpack dashboard, but it looks like it was yanked, according to the change history.  

Any specific recommendations or plan for re-adding?

**Comment by supnate** [comment]
Webpack dashboard was removed for two reasons:

1. It prevents other information to show such as the listening port.
2. It prevents the output to be streamed to other pipe lines. For example if `server.js` is integrated to some other tool, the output should be plain text.

Since Rekit creates the most general project, so the plugin isn't suitable enough. You can add it back for the created project very easy as you see in the change history.

I've removed it also from readme, sorry for the confusion,
