### ISSUE TITLE
Sidebar menu highlight bug

### ISSUE THREAD

**Issue by henryzp** [supnate/rekit#47]
when I use NavLink，link this: 

```
<NavLink to={path} activeClassName="active">{item.name || item.path}</NavLink>
```

when I jump to other menu，other menu cannot highlight，still this menu highlight。。I should do like this:

```
<NavLink  onClick={()=>{this.forceUpdate()}}  to={path} activeClassName="active">{item.name || item.path}</NavLink>
```

Is there a better way?

**Comment by supnate** [comment]
This seems to be a common problem when using Redux and React Router v4. You could refer to https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md or ask a question on [StackOverflow](https://stackoverflow.com/) since it is actually not related with Rekit.

BTW, you workaround only works when user clicks the link button to change URL. If URL is changed by other links or API, it will not work.

**Comment by henryzp** [comment]
@supnate thx
