### ISSUE TITLE
Adding NPM dependencies

### ISSUE THREAD

**Issue by mtwallet** [supnate/rekit#80]
Hi there,

Congrats on a great looking project!

I've just created a fresh install and added material-ui as a dependency using `npm i material-ui@next --save`. When I try and run the project I get an error saying it cannot resolve the package. Am I doing something wrong?

Many thanks in advance.

**Comment by supnate** [comment]
What's the error? Could you paste it here?

**Comment by mtwallet** [comment]
`ERROR in ./src/features/home/DefaultPage.js
Module not found: Error: Can't resolve 'material-ui/RaisedButton' in '/Applications/MAMP/htdocs/rekitTest/src/features/home'
 @ ./src/features/home/DefaultPage.js 28:20-55
 @ ./src/features/home/index.js
 @ ./src/common/routeConfig.js
 @ ./src/index.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?http://0.0.0.0:6075 ./styles/index.scss ./index`

**Comment by supnate** [comment]
I tried and got the same error. Then I checked that `node_modules\material-ui\RaisedButton` directory doesn't exist. It seems they have moved RaisedButton somewhere else for the `next` build. Then checked the new docs at https://material-ui-next.com/api/button/ . It shows they have used <Button raised .../> instead of RaisedButton.

**Comment by mtwallet** [comment]
Thanks for looking into that, I didn't see that they'd moved the docs. I appreciate the help and look forward to testing out Rekit.
